#!/bin/zsh
# Copyright 2026 Meni Tasa
# SPDX-License-Identifier: LicenseRef-PolyForm-Perimeter-1.0.0
#
# Render the `jitpass` cask for jitpass/homebrew-tap: one install that puts
# JitPass.app in /Applications and the jit inside it on PATH, with shell
# completions. One product, one number: the app's version IS the jit
# version it bundles, with a fourth part for an app-only release
# (1.5.8 ships jit 1.5.8; 1.5.8.1 is the same jit with an app fix), so
# `brew info jitpass` says which jit a user has without a second number.
# release.yml refuses a tag that does not start with the pinned jit.version.
#   scripts/cask.sh <app-version> <sha256>
set -euo pipefail
cd "$(dirname "$0")/.."
source scripts/lib.sh
version="${1:?app version}"
sha="${2:?sha256}"
cat <<CASK
# Generated by jitpass/jit-app scripts/cask.sh. DO NOT EDIT.
cask "jitpass" do
  version "$version"
  sha256 "$sha"

  url "https://github.com/jitpass/jit-app/releases/download/v#{version}/$APP_NAME-#{version}-arm64.zip"
  name "JitPass"
  desc "Local-first developer secret runtime: the jit CLI and its menu bar app"
  homepage "https://github.com/jitpass/jit"

  livecheck do
    skip "Updated by the jit-app release workflow."
  end

  conflicts_with cask: "jit-app"
  depends_on arch: :arm64
  depends_on macos: :sonoma

  app "$APP_NAME.app"
  binary "#{appdir}/$APP_NAME.app/$HELPER_JIT_REL"
  bash_completion "#{appdir}/$APP_NAME.app/Contents/Resources/completions/jit.bash"
  fish_completion "#{appdir}/$APP_NAME.app/Contents/Resources/completions/jit.fish"
  zsh_completion "#{appdir}/$APP_NAME.app/Contents/Resources/completions/_jit"

  # The cask cannot open the app itself. Homebrew runs \`postflight_steps\`
  # in a sandbox with (deny lsopen), so \`open\` fails there by design
  # (checked against Homebrew 7.0.4), and the legacy \`postflight\` block
  # that could is deprecated: it warns every user of a third-party tap and
  # will stop loading. So the caveat says it, and staying open across an
  # upgrade is the app's own job, not the cask's.
  uninstall quit: "$BUNDLE_ID"

  # What is left when nobody used Settings > Remove JitPass first. zap
  # deletes; it cannot put a migrated file back, and the vault is the only
  # thing that can, so the caveat says to remove from the app instead.
  zap trash: [
    "~/.jit",
    "~/Library/Application Support/jitpass",
    "~/Library/Caches/$BUNDLE_ID",
    "~/Library/HTTPStorages/$BUNDLE_ID",
    "~/Library/LaunchAgents/com.jitpass.agent.plist",
    "~/Library/Preferences/$BUNDLE_ID.plist",
    "~/Library/Saved Application State/$BUNDLE_ID.savedState",
  ]

  caveats <<~EOS
    Open JitPass once to finish setup (it lives in the menu bar):
      open -a JitPass
    jit's background service keeps running across upgrades and restarts
    itself onto the new binary. Your vault is never touched by an install,
    upgrade or uninstall.
    To leave: Settings > Remove JitPass puts every file back first. A plain
    uninstall, or --zap, leaves migrated files pointing at a vault.
  EOS
end
CASK
