#!/bin/zsh
# Copyright 2026 Meni Tasa
# SPDX-License-Identifier: LicenseRef-PolyForm-Perimeter-1.0.0
#
# Render the temporary `jit-app` cask for jitpass/homebrew-tap. Temporary
# because phase 2 folds the app into the `jitpass` cask; until then the app
# depends on the CLI cask for the agent it talks to.
#   scripts/cask.sh <version> <sha256>
set -euo pipefail
cd "$(dirname "$0")/.."
source scripts/lib.sh
version="${1:?version}"
sha="${2:?sha256}"
cat <<CASK
# Generated by jitpass/jit-app scripts/cask.sh. DO NOT EDIT.
cask "jit-app" do
  version "$version"
  sha256 "$sha"

  url "https://github.com/jitpass/jit-app/releases/download/v#{version}/$APP_NAME-#{version}-arm64.zip"
  name "JitPass"
  desc "Menu bar app for jit, the just-in-time secrets tool"
  homepage "https://github.com/jitpass/jit-app"

  depends_on cask: "jitpass/tap/jitpass"
  depends_on macos: ">= :sonoma"
  depends_on arch: :arm64

  app "$APP_NAME.app"

  zap trash: "~/Library/Preferences/$BUNDLE_ID.plist"
end
CASK
