#!/bin/zsh
# Copyright 2026 Meni Tasa
# SPDX-License-Identifier: LicenseRef-PolyForm-Perimeter-1.0.0
#
# Render the `jitpass` cask for jitpass/homebrew-tap: one install that puts
# JitPass.app in /Applications and the jit inside it on PATH, with shell
# completions. The cask version is "<jit>,<app>" so `brew upgrade` follows
# either moving and `brew info` says which jit a user has.
#   scripts/cask.sh <app-version> <sha256>
set -euo pipefail
cd "$(dirname "$0")/.."
source scripts/lib.sh
version="${1:?app version}"
sha="${2:?sha256}"
cat <<CASK
# Generated by jitpass/jit-app scripts/cask.sh. DO NOT EDIT.
cask "jitpass" do
  version "$(jit_version),$version"
  sha256 "$sha"

  url "https://github.com/jitpass/jit-app/releases/download/v#{version.csv.second}/$APP_NAME-#{version.csv.second}-arm64.zip"
  name "JitPass"
  desc "Local-first developer secret runtime: the jit CLI and its menu bar app"
  homepage "https://github.com/jitpass/jit"

  livecheck do
    skip "Updated by the jit-app release workflow."
  end

  conflicts_with cask: "jit-app"
  depends_on arch: :arm64
  depends_on macos: :sonoma

  app "$APP_NAME.app"
  binary "#{appdir}/$APP_NAME.app/Contents/MacOS/jit"
  bash_completion "#{appdir}/$APP_NAME.app/Contents/Resources/completions/jit.bash"
  fish_completion "#{appdir}/$APP_NAME.app/Contents/Resources/completions/jit.fish"
  zsh_completion "#{appdir}/$APP_NAME.app/Contents/Resources/completions/_jit"

  uninstall quit: "$BUNDLE_ID"

  caveats <<~EOS
    jit's background service keeps running across upgrades and restarts
    itself onto the new binary. Your vault is never touched by an install,
    upgrade or uninstall.
  EOS
end
CASK
